import numpy as np
from scipy.integrate import odeint
import matplotlib.pyplot as plt

class Modulo:
    def __init__(self, n):
        self.n = n
    
    def model_trafic(self):
       ...
    def calculo_raices(self):
        ...
    def ajuste_curvas(self):
        ...
    def derivada_velocidad_aceleracion(self):
        ...
    def Acumulacion_integrales(self):
        ...
    def Trazado_trayectorias(self):
        ...
    def Trapecio(self):
        ...
    def Masa_amortiguador(self):
        ...
    def analogia_masa_amortiguador(self):
        ...
    def Teorias_colas_simples(self):
        ...
    def Teorias_colas_multiples(self):
        ...
    def Monte_Carlo(self):
        ...
    